Bugfix error in RenewAllFixturesBaseCommand
Bugfix this error:
```
  File "bx_django_utils/test_utils/fixtures.py", line 143, in handle
    for no, fixture in enumerate(fixtures_registry, 1):
  File "bx_django_utils/test_utils/fixtures.py", line 87, in __iter__
    for FixtureClass, fixtures in sorted(self.fixtures.items()):
TypeError: '<' not supported between instances of 'type' and 'type'
```

Because class objects can't be sorted by themselves.
Just replace the class object with `FixtureClass.__name__` to fix this.

Additional changes:

* Enhance error message if fixture file doesn't exist
* unify errors